// No HTTP server or browser process: exercise the production bundle with real WASM.
import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs/promises';
import {JSDOM} from 'jsdom';
test('one code editor, one active formula host, full-source history and file opening',async()=>{
  const dom=new JSDOM(await fs.readFile(new URL('../web/index.html',import.meta.url),'utf8'),{url:'http://localhost:4321',pretendToBeVisual:true});
  const win=dom.window;
  for(const name of ['window','Window','document','navigator','HTMLElement','Element','Node','Text','MutationObserver','DOMParser','getComputedStyle','KeyboardEvent'])Object.defineProperty(globalThis,name,{value:name==='window'?win:win[name],configurable:true});
  globalThis.requestAnimationFrame=win.requestAnimationFrame.bind(win);globalThis.cancelAnimationFrame=win.cancelAnimationFrame.bind(win);
  globalThis.innerWidth=1280;globalThis.innerHeight=900;
  globalThis.ResizeObserver=class{observe(){}unobserve(){}disconnect(){}};
  win.Range.prototype.getClientRects=()=>[];win.Range.prototype.getBoundingClientRect=()=>({x:0,y:0,top:0,left:0,right:0,bottom:0,width:0,height:0});
  win.HTMLElement.prototype.scrollIntoView=()=>{};
  document.fonts={ready:Promise.resolve()};
  const initial='中文😀\n$a/b$ and $x$';
  globalThis.fetch=async(url,opts)=>{
    if(url==='/core.wasm')return new Response(await fs.readFile(new URL('../web/core.wasm',import.meta.url)),{headers:{'Content-Type':'application/wasm'}});
    if(url==='/api/status')return Response.json({available:false,attachments:true});
    if(url==='/api/render')return Response.json({items:[]});
    if(url==='/api/preview')return Response.json({pages:[]});
    if(url==='/api/prewarm'){
      const body=JSON.parse(opts.body),start=body.source.indexOf('cancel(a)');
      return Response.json({results:start<0?[]:[{key:body.source,failed:false,items:[{id:`${start}:${start+9}:0:0`,template_source:'cancel(a)',svg:'<svg xmlns="http://www.w3.org/2000/svg"/>',width:12,height:12,base_font_size_pt:1,base_font_height_pt:1,environment_font_size_pt:12}]}]});
    }
    if(url==='/api/files')return Response.json({root:'project',files:['main.typ']});
    if(url==='/api/file')return Response.json({source:initial});
    if(url==='/api/lsp')return Response.json({result:null,diagnostics:[]});
    throw new Error('Unexpected request '+url);
  };
  const {editorView:v,destroyEditor}=await import('../web/editor.bundle.js');assert.ok(v,'bundle initialized: '+document.getElementById('status')?.textContent);
  assert.equal(v.state.doc.toString(),initial,'initial file must be read from disk');
  assert.equal(document.querySelectorAll('.cm-editor').length,1);
  v.scrollDOM.dispatchEvent(new win.WheelEvent('wheel',{ctrlKey:true,deltaY:-100,bubbles:true,cancelable:true}));
  await Promise.resolve();
  assert.equal(document.documentElement.style.getPropertyValue('--editor-size'),'17px','Ctrl+wheel changes the editor and formula base size');
  const click=id=>document.getElementById(id).click();
  v.dispatch({selection:{anchor:7}});click('edit-formula');
  assert.equal(document.querySelectorAll('.cm-content #canvas').length,1);
  assert.equal(v.state.doc.toString(),initial,'entering a formula is lossless');
  const input=text=>document.getElementById('keyboard').dispatchEvent(new win.InputEvent('beforeinput',{inputType:'insertText',data:text,bubbles:true,cancelable:true}));
  input('q');assert.notEqual(v.state.doc.toString(),initial);
  click('finish-formula');assert.equal(document.querySelectorAll('.cm-content #canvas').length,0);
  click('undo');assert.equal(v.state.doc.toString(),initial,'formula and source share undo');
  v.dispatch({selection:{anchor:5}});
  v.contentDOM.dispatchEvent(new win.KeyboardEvent('keydown',{key:'ArrowRight',bubbles:true,cancelable:true}));
  assert.equal(document.querySelectorAll('.cm-content #canvas').length,1,'right arrow enters from the formula boundary');
  click('finish-formula');
  v.dispatch({selection:{anchor:10}});
  v.contentDOM.dispatchEvent(new win.KeyboardEvent('keydown',{key:'ArrowLeft',bubbles:true,cancelable:true}));
  assert.equal(document.querySelectorAll('.cm-content #canvas').length,1,'left arrow enters from the end boundary');
  click('finish-formula');
  click('redo');assert.match(v.state.doc.toString(),/q/);
  v.dispatch({selection:{anchor:v.state.doc.length}});click('insert-inline');
  assert.equal(document.querySelectorAll('.cm-editor').length,1);
  assert.equal(document.querySelectorAll('.cm-content #canvas').length,1);
  input('\\');input('frac');
  assert.equal(document.querySelectorAll('.cm-content #canvas').length,1,'incomplete command keeps the shared host');
  document.getElementById('keyboard').dispatchEvent(new win.KeyboardEvent('keydown',{key:'Enter',bubbles:true,cancelable:true}));
  assert.ok(document.querySelector('.fraction'));
  input('a');click('finish-formula');
  const before=v.state.doc.toString();v.dispatch({selection:{anchor:v.state.doc.length}});click('insert-display');
  assert.equal(document.querySelectorAll('.cm-content #canvas').length,1);
  input('z');click('finish-formula');assert.notEqual(v.state.doc.toString(),before);
  click('source-mode');assert.equal(document.querySelectorAll('.cm-content .formula-widget').length,0);
  const macro='#let fixed(x) = $#x + cancel(a)$';
  v.dispatch({changes:{from:0,to:v.state.doc.length,insert:macro},selection:{anchor:macro.indexOf('$')+1}});click('edit-formula');
  for(let i=0;i<30&&!document.querySelector('img[alt="cancel(a)"]');i++)await new Promise(resolve=>setTimeout(resolve,30));
  assert.ok(document.querySelector('img[alt="cancel(a)"]'),'a definition with no real call uses its warmed fixed Raw SVG');
  assert.equal(v.state.doc.toString(),macro,'preheating never inserts an instance into the document');
  destroyEditor();win.close();
});
