"""Build a Windows x64 portable ZIP, then test the frozen application offscreen.

Run build-release.cmd --help. No desktop window is started by this script.
Outputs are never overwritten; intermediate files stay under target/packaging.
"""
import argparse
import hashlib
import importlib.metadata
import json
import os
import platform
import re
import shutil
import struct
import subprocess
import sys
import time
import uuid
import zipfile
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent


def run(arguments, **kwargs):
    print('+ ' + subprocess.list2cmdline(list(map(str, arguments))), flush=True)
    subprocess.run(list(map(str, arguments)), cwd=ROOT, check=True, **kwargs)


def sha256(path):
    digest = hashlib.sha256()
    with path.open('rb') as stream:
        for part in iter(lambda: stream.read(1024 * 1024), b''):
            digest.update(part)
    return digest.hexdigest()


def require_x64(path):
    """Reject missing helpers and accidental ARM64/x86 packages before bundling."""
    with path.open('rb') as stream:
        if stream.read(2) != b'MZ':
            raise ValueError(f'Not a Windows executable: {path}')
        stream.seek(0x3c)
        offset = struct.unpack('<I', stream.read(4))[0]
        stream.seek(offset)
        if stream.read(4) != b'PE\0\0' or stream.read(2) != b'\x64\x86':
            raise ValueError(f'Expected an x64 Windows executable: {path}')


def find_tinymist(explicit=None):
    configured = explicit or os.environ.get('TINYMIST_BIN')
    if configured:
        path = Path(configured).resolve()
        if not path.is_file():
            raise ValueError(f'Tinymist does not exist: {path}')
        return path
    found = shutil.which('tinymist.exe')
    if found:
        return Path(found).resolve()
    profile = Path(os.environ.get('USERPROFILE', Path.home()))
    paths = [p for editor in ('.vscode', '.vscode-insiders', '.cursor')
             for p in (profile / editor / 'extensions').glob('myriad-dreamin.tinymist-*/out/tinymist.exe')]
    if paths:
        return max(paths, key=lambda p: p.stat().st_mtime).resolve()
    raise ValueError('Tinymist not found. Use --tinymist PATH or explicitly choose --without-tinymist.')


def tinymist_license(binary, explicit=None):
    if explicit:
        path = Path(explicit).resolve()
        if not path.is_file():
            raise ValueError(f'Tinymist license does not exist: {path}')
        return path
    for directory in (binary.parent, binary.parent.parent):
        for name in ('LICENSE.txt', 'LICENSE', 'LICENSE-APACHE'):
            path = directory / name
            if path.is_file():
                return path
    raise ValueError('No license beside Tinymist. Supply --tinymist-license PATH from the same distribution.')


def write_spec(path, assets, binaries):
    # Paths are Python literals in a spec file, never shell fragments.
    path.write_text(f'''# Generated by tools/build_release.py
a = Analysis([{str(ROOT / 'tools/release_entry.py')!r}],
    pathex=[{str(ROOT)!r}], binaries={binaries!r}, datas={assets!r},
    hiddenimports=['PyQt5.QtWebEngineWidgets'],
    excludes=['PySide2', 'PySide6', 'PyQt6', 'desktop.test_desktop'])
pyz = PYZ(a.pure)
exe = EXE(pyz, a.scripts, [], exclude_binaries=True, name='TypFormula',
    debug=False, strip=False, upx=False, console=False)
coll = COLLECT(exe, a.binaries, a.datas, strip=False, upx=False, name='TypFormula')
''', encoding='utf-8')


def collect_licenses(destination, tinymist, license_file):
    destination.mkdir(parents=True)
    for source, name in [('COPYING', 'TypFormula-COPYING'), ('docs/LYX-CREDITS', 'LYX-CREDITS'),
                         ('fonts/NOTICE', 'fonts-NOTICE'), ('vendor/typst/LICENSE', 'Typst-LICENSE'),
                         ('vendor/typst/NOTICE', 'Typst-NOTICE'), ('vendor/typst/UPSTREAM.md', 'Typst-UPSTREAM.md')]:
        shutil.copy2(ROOT / source, destination / name)
    if tinymist:
        shutil.copy2(license_file, destination / 'Tinymist-LICENSE.txt')
    # Keep installed distribution notices and metadata rather than guessing their terms.
    for name in ('PyQt5', 'PyQt5-Qt5', 'PyQt5-sip', 'PyQtWebEngine', 'PyQtWebEngine-Qt5',
                 'PyInstaller', 'pyinstaller-hooks-contrib'):
        dist = importlib.metadata.distribution(name)
        folder = destination / name; folder.mkdir()
        (folder / 'METADATA.txt').write_text(dist.read_text('METADATA') or '', encoding='utf-8')
        for entry in dist.files or []:
            if any(word in entry.name.upper() for word in ('LICENSE', 'COPYING', 'NOTICE')):
                original = Path(dist.locate_file(entry))
                if original.is_file():
                    target = folder / str(entry).replace('..', '_').replace('\\', '_').replace('/', '_')
                    shutil.copy2(original, target)
    for base in (Path(sys.base_prefix), Path(sys.prefix)):
        for name in ('LICENSE.txt', 'LICENSE'):
            if (base / name).is_file():
                shutil.copy2(base / name, destination / 'Python-LICENSE.txt')
                return


def verify_layout(bundle, with_tinymist):
    required = ['TypFormula.exe', '_internal/bin/typformula.exe', '_internal/bin/typformula-layout.exe',
                '_internal/config/desktop-settings.json', '_internal/fonts/NewCMMath-Regular.otf',
                '_internal/fonts/NewCM10-Italic.otf']
    if with_tinymist:
        required.append('_internal/bin/tinymist.exe')
    for relative in required:
        if not (bundle / relative).is_file():
            raise ValueError(f'Missing packaged file: {relative}')
    for pattern in ('qwindows.dll', 'qoffscreen.dll', 'QtWebEngineProcess.exe', 'icudtl.dat', 'qtwebengine_resources.pak'):
        if not any(bundle.rglob(pattern)):
            raise ValueError(f'Missing Qt resource: {pattern}')


def main(argv=None):
    parser = argparse.ArgumentParser(description=__doc__)
    version = re.search(r'^version\s*=\s*"([^"]+)"', (ROOT / 'Cargo.toml').read_text(encoding='utf-8'), re.M)[1]
    parser.add_argument('--version', default=version, help='Release label (default: Cargo.toml version)')
    parser.add_argument('--output', type=Path, default=ROOT / 'dist', help='Output parent directory')
    parser.add_argument('--skip-build', action='store_true', help='Package existing target/server and target/adapter release executables')
    parser.add_argument('--backend', type=Path, help='Existing host executable; requires --skip-build')
    parser.add_argument('--adapter', type=Path, help='Existing layout executable; requires --skip-build')
    parser.add_argument('--fetch', action='store_true', help='Download locked Cargo dependencies before building')
    choice = parser.add_mutually_exclusive_group()
    choice.add_argument('--tinymist', type=Path, help='Tinymist x64 executable (otherwise auto-discovered)')
    choice.add_argument('--without-tinymist', action='store_true', help='Explicitly build a basic edition without bundled language services')
    parser.add_argument('--tinymist-license', type=Path, help='License from the supplied Tinymist distribution')
    args = parser.parse_args(argv)
    if sys.platform != 'win32' or struct.calcsize('P') != 8 or platform.machine().lower() not in ('amd64', 'x86_64'):
        parser.error('Build with x64 Python on Windows.')
    if not re.fullmatch(r'[A-Za-z0-9][A-Za-z0-9.+-]{0,63}', args.version):
        parser.error('Invalid version label.')
    if (args.backend or args.adapter) and not args.skip_build:
        parser.error('--backend/--adapter require --skip-build.')
    if args.without_tinymist and args.tinymist_license:
        parser.error('--tinymist-license cannot be used with --without-tinymist.')
    if args.skip_build and args.fetch:
        parser.error('--fetch cannot be used with --skip-build.')
    # Fail before compiling if the packaging environment is incomplete.
    versions = {name: importlib.metadata.version(name) for name in
                ('PyInstaller', 'pyinstaller-hooks-contrib', 'PyQt5', 'PyQt5-Qt5', 'PyQt5-sip', 'PyQtWebEngine', 'PyQtWebEngine-Qt5')}
    run([sys.executable, '-c', 'from PyQt5 import QtWidgets, QtSvg, QtWebEngineWidgets'])
    tinymist = None if args.without_tinymist else find_tinymist(args.tinymist)
    license_file = tinymist_license(tinymist, args.tinymist_license) if tinymist else None
    if tinymist:
        require_x64(tinymist)
    tinymist_version = subprocess.check_output([str(tinymist), '--version'], text=True, encoding='utf-8',
        timeout=15, creationflags=subprocess.CREATE_NO_WINDOW).strip() if tinymist else None
    name = f'TypFormula-{args.version}-windows-x64' + ('-basic' if args.without_tinymist else '')
    output = args.output.resolve(); destination = output / name
    archive = output / (name + '.zip'); checksum = output / (name + '.zip.sha256')
    if any(p.exists() for p in (destination, archive, checksum)):
        raise ValueError('Output already exists. Choose a new --version or --output; nothing is overwritten.')
    work = ROOT / 'target' / 'packaging' / uuid.uuid4().hex
    work.mkdir(parents=True)
    if args.skip_build:
        backend = (args.backend or ROOT / 'target/server/release/typformula.exe').resolve()
        adapter = (args.adapter or ROOT / 'target/adapter/release/typformula-layout.exe').resolve()
    else:
        # Separate build directories never replace helpers used by a running editor.
        for manifest, target in [('Cargo.toml', 'server'), ('native-adapter/Cargo.toml', 'adapter')]:
            if args.fetch:
                run(['cargo', 'fetch', '--locked', '--manifest-path', manifest])
            command = ['cargo', 'build', '--offline', '--locked', '--release', '--manifest-path', manifest,
                       '--target-dir', ROOT / 'target/package-build' / target, '--target', 'x86_64-pc-windows-msvc']
            if target == 'server':
                command += ['--bin', 'typformula']
            run(command)
        backend = ROOT / 'target/package-build/server/x86_64-pc-windows-msvc/release/typformula.exe'
        adapter = ROOT / 'target/package-build/adapter/x86_64-pc-windows-msvc/release/typformula-layout.exe'
    staging = work / 'helpers'; staging.mkdir()
    for source, filename in ((backend, 'typformula.exe'), (adapter, 'typformula-layout.exe')):
        require_x64(source); shutil.copy2(source, staging / filename)
    if tinymist:
        shutil.copy2(tinymist, staging / 'tinymist.exe')
    assets = [(str(ROOT / 'config/desktop-settings.json'), 'config'),
              (str(ROOT / 'fonts/NewCMMath-Regular.otf'), 'fonts'),
              (str(ROOT / 'fonts/NewCM10-Italic.otf'), 'fonts')]
    binaries = [(str(p), 'bin') for p in sorted(staging.glob('*.exe'))]
    spec = work / 'TypFormula.spec'; write_spec(spec, assets, binaries)
    run([sys.executable, '-m', 'PyInstaller', '--noconfirm', '--distpath', work / 'dist',
         '--workpath', work / 'build', spec])
    bundle = work / 'dist/TypFormula'
    verify_layout(bundle, bool(tinymist))
    # Run the *frozen* executable from another cwd with a non-ASCII path in the report.
    report = work / '离屏自检.json'
    tested = subprocess.run([str(bundle / 'TypFormula.exe'), '--self-test', str(report)],
                            cwd=work, timeout=240, creationflags=subprocess.CREATE_NO_WINDOW)
    result = json.loads(report.read_text(encoding='utf-8')) if report.is_file() else {}
    if tested.returncode or not result.get('ok'):
        raise RuntimeError(f'Frozen self-test failed; see {report}: {result.get("error", "no report")}')
    collect_licenses(bundle / 'licenses', tinymist, license_file)
    shutil.copytree(ROOT / 'docs', bundle / 'docs')
    shutil.copy2(ROOT / 'README.md', bundle / 'README.md')
    shutil.copy2(ROOT / 'AGENTS.md', bundle / 'AGENTS.md')
    shutil.copy2(ROOT / 'COPYING', bundle / 'COPYING')
    (bundle / 'fonts').mkdir()
    shutil.copy2(ROOT / 'fonts/NOTICE', bundle / 'fonts/NOTICE')
    engine_docs = bundle / 'vendor/typst'; engine_docs.mkdir(parents=True)
    for filename in ('UPSTREAM.md', 'LICENSE', 'NOTICE'):
        shutil.copy2(ROOT / 'vendor/typst' / filename, engine_docs / filename)
    (bundle / 'START-HERE.txt').write_text(
        'TypFormula ' + args.version + '\n\n解压整个目录后，双击 TypFormula.exe。不要只复制 exe。\n'
        '无需安装 Python、Rust 或 VS Code。用户数据位于 %LOCALAPPDATA%/TypFormula，设置位于 %APPDATA%/TypFormula。\n'
        + ('此基础版未包含 Tinymist；语言服务和实时预览需另行安装。\n' if args.without_tinymist else '已包含 Tinymist，可直接使用语言服务与实时预览。\n')
        + '使用教程：docs/tutorial.typ（教程所需的 latex-lookalike 包需要联网安装）。\n'
        '本构建通过离屏自检；真实窗口与 WebEngine 页面仍需发布前人工验收。\n', encoding='utf-8-sig')
    git = subprocess.run(['git', 'rev-parse', 'HEAD'], cwd=ROOT, capture_output=True, text=True)
    dirty = subprocess.run(['git', 'status', '--porcelain'], cwd=ROOT, capture_output=True, text=True)
    manifest = {'version': args.version, 'built_at': time.strftime('%Y-%m-%dT%H:%M:%SZ', time.gmtime()),
                'commit': git.stdout.strip() if git.returncode == 0 else None,
                'dirty': bool(dirty.stdout.strip()) if dirty.returncode == 0 else None,
                'python': sys.version, 'packages': versions, 'tinymist_version': tinymist_version, 'skip_build': args.skip_build,
                'helpers': {p.name: sha256(p) for p in staging.glob('*.exe')}, 'self_test': result}
    (bundle / 'release-manifest.json').write_text(json.dumps(manifest, ensure_ascii=False, indent=2), encoding='utf-8')
    output.mkdir(parents=True, exist_ok=True)
    shutil.copytree(bundle, destination)
    with zipfile.ZipFile(archive, 'x', compression=zipfile.ZIP_DEFLATED, compresslevel=6) as zipped:
        for path in sorted(destination.rglob('*')):
            if path.is_file():
                zipped.write(path, Path(name) / path.relative_to(destination))
    checksum.write_text(sha256(archive) + '  ' + archive.name + '\n', encoding='ascii')
    print(f'Portable directory: {destination}\nRelease ZIP: {archive}\nSHA256: {checksum}', flush=True)
    return 0


if __name__ == '__main__':
    try:
        raise SystemExit(main())
    except (OSError, ValueError, RuntimeError, subprocess.SubprocessError, importlib.metadata.PackageNotFoundError) as error:
        print(f'Release build failed: {error}', file=sys.stderr)
        if isinstance(error, importlib.metadata.PackageNotFoundError):
            print('Use a clean venv: python -m pip install -r tools/requirements-release.txt', file=sys.stderr)
        raise SystemExit(1)
